export default function TermsPage() {
  const domain = 'autograde.live'; // update to your actual domain
  const email  = 'dodoxuxumomo@gmail.com';
  const date   = 'June 2025';

  return (
    <LegalPage title="Terms of Service" updated={date}>
      <Section title="1. Acceptance of Terms">
        <p>By accessing or using AutoGrade.live ("Service"), operated at <strong>{domain}</strong>, you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
        <p>These Terms apply to all users, including teachers, administrators, and any other persons accessing the Service.</p>
      </Section>

      <Section title="2. Description of Service">
        <p>AutoGrade.live is an AI-powered grading platform that integrates with Google Classroom. It allows educators to:</p>
        <ul>
          <li>Create and publish assignments to Google Classroom</li>
          <li>Automatically grade student submissions using Google Gemini AI</li>
          <li>Sync AI-generated grades back to Google Classroom</li>
          <li>Manage grading jobs, view results, and analyze student performance</li>
        </ul>
      </Section>

      <Section title="3. Eligibility">
        <ul>
          <li>You must be at least 18 years old or the legal age of majority in your jurisdiction</li>
          <li>You must be a teacher, educator, or institution administrator using Google Classroom</li>
          <li>You must have a valid Google account with access to Google Classroom</li>
          <li>You are responsible for ensuring your use complies with your institution's policies</li>
        </ul>
      </Section>

      <Section title="4. Account and Authentication">
        <p>AutoGrade.live uses Google OAuth exclusively for authentication. By signing in, you grant us access to your Google Classroom courses, assignments, and student submissions as described in our Privacy Policy.</p>
        <p>You are responsible for maintaining the confidentiality of your account and for all activities under your account.</p>
      </Section>

      <Section title="5. Acceptable Use">
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service to grade content that violates applicable laws or regulations</li>
          <li>Attempt to reverse-engineer, hack, or exploit the platform</li>
          <li>Use the Service for any purpose other than legitimate educational grading</li>
          <li>Share student data beyond what is necessary for the grading function</li>
          <li>Misrepresent AI-generated grades as manually reviewed without disclosure</li>
          <li>Circumvent the billing system or attempt to exploit the free tier</li>
        </ul>
      </Section>

      <Section title="6. AI-Generated Content Disclaimer">
        <p>Grades, scores, remarks, and feedback produced by AutoGrade.live are generated by AI (Google Gemini) based on the rubric and answer key you provide. These outputs:</p>
        <ul>
          <li>Are <strong>not guaranteed to be accurate</strong> and should be reviewed by the educator before being treated as final</li>
          <li>Reflect the quality of the rubric and reference materials provided</li>
          <li>Should not be used as the sole basis for high-stakes academic decisions without human review</li>
        </ul>
        <p>By using the Service you accept responsibility for reviewing AI-generated grades before they are communicated to students.</p>
      </Section>

      <Section title="7. Student Data and Privacy">
        <p>As an educator using this Service, you are responsible for ensuring your use complies with applicable student privacy laws (including FERPA, COPPA, and any local equivalents).</p>
        <p>You represent that you have the authority and appropriate permissions to submit student work for AI analysis. Student submission content is processed by Google Gemini AI solely to generate grades and feedback and is not used for any other purpose.</p>
      </Section>

      <Section title="8. Billing and Payments">
        <ul>
          <li>Each account receives <strong>5 free grading submissions</strong></li>
          <li>Beyond the free tier, grading is billed from your wallet balance at actual AI/processing cost plus a 30% platform fee</li>
          <li>Wallet recharges are processed by Razorpay and are <strong>non-refundable</strong> unless required by law</li>
          <li>Minimum wallet recharge is ₹100</li>
          <li>We reserve the right to change pricing with 30 days notice</li>
        </ul>
      </Section>

      <Section title="9. Intellectual Property">
        <p>The AutoGrade.live platform, including its code, design, and branding, is owned by us and protected by applicable intellectual property laws.</p>
        <p>You retain ownership of all content you upload, including question papers, rubrics, and answer keys. You grant us a limited, non-exclusive license to process this content solely to provide the Service.</p>
      </Section>

      <Section title="10. Limitation of Liability">
        <p>To the maximum extent permitted by law, AutoGrade.live shall not be liable for:</p>
        <ul>
          <li>Inaccurate or incorrect AI-generated grades</li>
          <li>Data loss due to technical failures</li>
          <li>Interruption of service</li>
          <li>Indirect, incidental, or consequential damages arising from use of the Service</li>
        </ul>
        <p>Our total liability shall not exceed the amount you paid for the Service in the 3 months preceding the claim.</p>
      </Section>

      <Section title="11. Termination">
        <p>We reserve the right to suspend or terminate your account if you violate these Terms. You may delete your account at any time by contacting us. Upon termination, your wallet balance is forfeited unless otherwise required by law.</p>
      </Section>

      <Section title="12. Changes to Terms">
        <p>We may update these Terms from time to time. Significant changes will be communicated via email or a notice on the platform. Continued use after changes take effect constitutes acceptance of the new Terms.</p>
      </Section>

      <Section title="13. Governing Law">
        <p>These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts of India.</p>
      </Section>

      <Section title="14. Contact">
        <p>For questions about these Terms:</p>
        <p><strong>Email:</strong> <a href={`mailto:${email}`} style={{color:'#34d399'}}>{email}</a></p>
        <p><strong>Website:</strong> <a href={`https://${domain}`} style={{color:'#34d399'}}>{domain}</a></p>
      </Section>
    </LegalPage>
  );
}

function LegalPage({ title, updated, children }) {
  return (
    <div style={{minHeight:'100vh',background:'#020817',color:'#f1f5f9',fontFamily:'Inter,sans-serif'}}>
      <div style={{position:'fixed',inset:0,background:'linear-gradient(to bottom,#020817,#0f172a,#020817)',pointerEvents:'none'}}/>
      <div style={{position:'relative',zIndex:1,maxWidth:860,margin:'0 auto',padding:'48px 32px 80px'}}>
        <div style={{marginBottom:48}}>
          <a href="/" style={{display:'inline-flex',alignItems:'center',gap:10,textDecoration:'none',marginBottom:40}}>
            <div style={{width:36,height:36,borderRadius:10,background:'rgba(16,185,129,0.1)',border:'1px solid rgba(16,185,129,0.2)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:18}}>✓</div>
            <span style={{fontSize:17,fontWeight:600,color:'#f1f5f9',letterSpacing:'-0.02em'}}>AutoGrade<span style={{color:'#475569',fontWeight:400}}>.ai</span></span>
          </a>
          <h1 style={{fontSize:'clamp(28px,4vw,44px)',fontWeight:600,letterSpacing:'-0.02em',marginBottom:12}}>{title}</h1>
          <p style={{fontSize:13,color:'#475569'}}>Last updated: {updated}</p>
        </div>
        <div style={{display:'flex',flexDirection:'column',gap:32}}>
          {children}
        </div>
        <div style={{marginTop:64,paddingTop:24,borderTop:'1px solid rgba(255,255,255,0.07)',display:'flex',gap:24,flexWrap:'wrap'}}>
          <a href="/" style={{color:'#475569',fontSize:13,textDecoration:'none'}}>← Back to AutoGrade.ai</a>
          <a href="/privacy" style={{color:'#475569',fontSize:13,textDecoration:'none'}}>Privacy Policy</a>
          <a href="/terms" style={{color:'#475569',fontSize:13,textDecoration:'none'}}>Terms of Service</a>
        </div>
      </div>
      <style>{`
        p { color:#94a3b8; font-size:14px; line-height:1.8; margin-bottom:12px; }
        ul { color:#94a3b8; font-size:14px; line-height:1.8; padding-left:20px; margin-bottom:12px; }
        ul li { margin-bottom:4px; }
        strong { color:#f1f5f9; }
      `}</style>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div>
      <h2 style={{fontSize:18,fontWeight:600,color:'#f1f5f9',marginBottom:14,letterSpacing:'-0.01em'}}>{title}</h2>
      {children}
    </div>
  );
}
